from pydantic import BaseModel, Field
from typing import List

class Answer(BaseModel):
    """
    Pydantic Schema of the final response generated for the query.
    """
    answer: str | None = Field(
        description="The final answer generated to the query"
        )
    reasoning_summary: str = Field(
        description="A concise summary of the reasoning used to support the answer."
    )

class SynthesizerResult(BaseModel):
    """
    Pydantic Schema for the final synthesizer result with answer and citations
    """
    answer: Answer = Field(
        description="The Answer Schema generated by the synthesizer"
    )
    citations: List[dict] = Field(
        description="The actual chunks used for answer synthesis"
    )